### PR TITLE
New architecture support

### PR DESCRIPTION
**Pull request by zoontek**

### CODE REVIEW

**Comment by The-White-Fang** [comment]
Hey, is this ready to be used with new architecture?
I tried adding it to my project but it threw some errors. I tried on a bare react-native app with no dependencies.
Thanks for the fantastic package BTW.

**Comment by zoontek** [comment]
@The-White-Fang Yes, what are the errors?

**Comment by The-White-Fang** [comment]
`Execution failed for task ':react-native-bootsplash:buildCodegenCLI'.`
That's about it. It seems very generic error and I can't seem to figure out why it is throwing it.

**Comment by zoontek** [comment]
@The-White-Fang Until new arch is enable by default, I only support latest RN version. Could you confirm that you are using 0.72? Does it fails on iOS or Android?

**Comment by The-White-Fang** [comment]
Yes, I tried running it on 0.72.3 which I believe is the latest

**Comment by zoontek** [comment]
Did you went to the android directory and ran `./gradlew generateCodegenArtifactsFromSchema`?

**Comment by The-White-Fang** [comment]
I didn't earlier. But if I run it now, it throws the same error.

**Comment by zoontek** [comment]
@The-White-Fang Maybe open an issue on the react native repository.

**Pull request merged**
