### PR TITLE
feat: Adds conditional assets generations

### PR DESCRIPTION
**Pull request by nazmeln**
# Summary
Add functionality to generate assets for Android and iOS separately. It's useful when an app has 2 different splash screens for each platform or is developed only for iOS or Android. It impacts CLI script options.

### What's required for testing (prerequisites)?
- yarn install
- run CLI script inside example folder and try to generate assets for iOS or Android separately.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅    |
| Android |    ✅     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [ ] I added a sample use of the API in the example project (`example/App.tsx`)

### CODE REVIEW

**Comment by zoontek** [comment]
Thanks, this is a good idea!

I think it could be better to only have `--platforms=android,ios` (with `parse: (value) => value.split(",")` and `platforms.includes("ios")`)

WDYT?

**Comment by nazmeln** [comment]
@zoontek Good suggestion, updated :)

**Comment by zoontek** [comment]
LGTM 👍

**Comment by zoontek** [comment]
It's released: https://github.com/zoontek/react-native-bootsplash/releases/tag/4.6.0

**Pull request merged**
