### PR TITLE
[Feature] Android use layout XML instead of a plain drawable

### PR DESCRIPTION
**Pull request by krakz999**
With this PR bootsplash is using an android layout as splash screen instead of a plain drawable, making it easier to customize (add more images, texts, etc) or apply styling like scaling.

It also eliminates the need for RNBootSplashActivity, the deep linking workaround, and makes android installation process a bit shorter (2 steps from 4+1 steps).

### CODE REVIEW

**Comment by zoontek** [comment]
@krakz999 This looks neat! I'll review it this week-end.

**Comment by zoontek** [comment]
@krakz999 I just gave it a try, and I found one regression. In the current version, the logo is visible immediately at start, allowing continuity between the app logo and the splash screen.



But in your version, as the splash screen is only displayed when `MainActivity.onCreate` is called, it starts with a blank screen first, then the layout / logo fades in.

ezgif com-resize

**Comment by krakz999** [comment]
> @krakz999 I just gave it a try, and I found one regression. In the current version, the logo is visible immediately at start, allowing continuity between the app logo and the splash screen.
> 
> 
> 
> But in your version, as the splash screen is only displayed when `MainActivity.onCreate` is called, it starts with a blank screen first, then the layout / logo fades in.
> 
> ezgif com-resize

Hey, try the latest (updated Readme file, so android setup became 3 steps)

Just put this into your styles.xml: ```<item name="android:windowDisablePreview">true</item>```

**Comment by zoontek** [comment]
@krakz999 This seems to work, but is clearly not recommended: https://developer.android.com/topic/performance/vitals/launch-time#themed

**Comment by krakz999** [comment]
@zoontek yeah, for general usage it's probably better to keep this the way it is now

**Comment by zoontek** [comment]
@krakz999 I think we need to tackle the non-support of `android:background` [in React Native directly](https://github.com/facebook/react-native/issues/9072).
If we reset the background at JS bundle init, this lib could extend it, the same way it does on iOS.

This could remove the `BootTheme` and the `SplashActivity` config entirely.

**Comment by aiingstan** [comment]
So currently, could you guide me on what is the suggested way/workaround to use drawable image resources as the background instead of a solid color? @zoontek @krakz999

**Comment by zoontek** [comment]
@aiingstan Following the README allows you to use drawable resources, which can include images.

**Comment by aiingstan** [comment]
@zoontek Thanks for such a fast response. I'm sorry but I actually mean how can I make the image fullscreen? I set the image drawable but it displayed strangely (images are exported by AI with different sizes). I'm most certainly sure this is not related to your library but an Android question instead, but could you give a hint? Code as below:
```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <!-- is it possible that I make this image fullscreen?     -->
        <bitmap android:src="@drawable/splash_background" />
    </item>
    <item>
        <bitmap
            android:src="@mipmap/bootsplash_logo"
            android:gravity="center" />
    </item>
</layer-list>

```

**Comment by zoontek** [comment]
You can try using `android:gravity: "fill"`

See Android documentation https://developer.android.com/guide/topics/resources/drawable-resource for more informations.

**Comment by aiingstan** [comment]
Yes, it seems to be possible as #17 OP used an image drawable.
I'll try it, thank you a lot!👍

**Pull request closed without merging**
