### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by giacomocerquone**
update java init method to show

### CODE REVIEW

**Comment by zoontek** [comment]
The version currently on master uses `init`: https://github.com/zoontek/react-native-bootsplash/blob/master/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplash.java#L24

**Comment by giacomocerquone** [comment]
? The version I installed from npmjs uses show... so should the Readme represent the npm version of the branch version? @zoontek

**Comment by zoontek** [comment]
The latest version on npm uses init too. It seems relevant with you other issue (generate-bootsplash not found).

Could you check in node_modules/react-native-bootsplash/package.json which version is installed?

**Comment by zoontek** [comment]
Exactly the version on master: https://unpkg.com/browse/react-native-bootsplash@2.2.4/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplash.java

**Pull request closed without merging**
