### PR TITLE
Fix open intent main activity

### LINKED ISSUE #8: getApplicationContext().getPackageName() can return an inappropriate string
### 💻 My environment

- react-native-bootsplash version: 0.1.1
- Platform: android

### 🕵️‍♂️ Reproducing the issue

If your code isn't located at the place expected by this assumption https://github.com/zoontek/react-native-bootsplash/blob/60f7e216d626264e72f5efdad97672162324de7f/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java#L15-L16 (`getApplicationContext().getPackageName()`)

(My case: white labeled app with dynamic application id that's doesn't match the classes path)

### 🤞Solution

Your solution after a private discussion: 

https://developer.android.com/guide/topics/manifest/meta-data-element

```xml
    <activity
      android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
      android:theme="@style/BootTheme"> <!-- apply the theme you created at step 3. -->
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>

<meta-data android:name=“started” android:value=“com.my.ns” />
    </activity>
```

### Workaround

Use your own class for the activity. Eg for me with android-pre x

```java
package com.my.ns;

import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;

public class RNBootSplashActivityPackageNameWorkaround extends AppCompatActivity {

  @Override
  protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    try {
      startActivity(new Intent(this, MainActivity.class));
      finish();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
```

```xml
      <activity
        android:name=".RNBootSplashActivityPackageNameWorkaround"
        android:theme="@style/SplashTheme"
        >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
```

### PR DESCRIPTION
**Pull request by luancurti**
Fix wrong package name and crash on open `MainActivity`

### CODE REVIEW

**Comment by zoontek** [comment]
Hi @luancurti. This just restore the [initial behavior](https://github.com/zoontek/react-native-bootsplash/blob/b985ef97a5a65ab737982956ecbd3c3b364646d5/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java#L15) of the Activity.

It does not close #8 since the issue described by @MoOx is not this (his project entry point is not named `.MainActivity`)

It also remove [this fix](https://github.com/zoontek/react-native-bootsplash/pull/16).

**Comment by luancurti** [comment]
Hi @zoontek the problem here is the packageName is wrong testing with example the code try to open `o.MainActivity` I've tested with this code and this works I've considered this fix the #8 because the crash on Open `MainActivity` how we can fix this? there are any other option or this code fix this problem? This library is not working because this problem

**Comment by zoontek** [comment]
@luancurti What's your app namespace? Do you use build flavors?

**Comment by luancurti** [comment]
> @luancurti What's your app namespace? Do you use build flavors?

No I don't is `com.gympass` I don't understand why this problem occurs because the problem occurs in the example app is any config of my `Android Studio` ? I've found various documentations in `Android Developer Docs` that suggested the use of the `getPackageName` here are an example https://stackoverflow.com/questions/6589797/how-to-get-package-name-from-anywhere

**Comment by luancurti** [comment]
I use the variable `applicationId` https://developer.android.com/studio/build/application-id.html in this link are the note explain how `getPackageName` get this 

`Note: The application ID used to be directly tied to your code's package name; so some Android APIs use the term "package name" in their method names and parameter names, but this is actually your application ID. For example, the Context.getPackageName() method returns your application ID. There's no need to ever share your code's true package name outside your app code.`

There is the problem?

**Comment by zoontek** [comment]
@luancurti Please open an issue and submit your Gradle config.

**Comment by zoontek** [comment]
(I also set `applicationId` in our production app without any issue)

**Comment by zoontek** [comment]
I'm closing this since `getPackageName` returns the `applicationSuffixId` and will break a lot of users builds.

**Pull request closed without merging**
