### PR TITLE
WIP: 4.0.0

### PR DESCRIPTION
**Pull request by zoontek**
Following the https://github.com/zoontek/react-native-bootsplash/issues/237 issue

This PR is a WIP of a new major version that will switch from `android:background` to `android:windowBackground` logic, remove the need of a custom `RNBootSplashActivity` and support https://developer.android.com/about/versions/12/features/splash-screen on Android 12+.

To allow logo animation continuation at start, we will expose two constants: `statusBarHeight` and `navigationBarHeight` (which can be user with negative margins to prevent "jump")

- [ ] Switch to `Dialog` + `windowBackground` logic
- [x] Support `windowSplashScreenBackground` on Android 12+
- [ ] Expose `statusBarHeight` and `navigationBarHeight`
- [x] Update JS module
- [x] Update documentation
- [x] Write a `MIGRATION` guide

### CODE REVIEW

**Comment by zoontek** [comment]
First alpha is available: `yarn add react-native-bootsplash@next`

**Comment by andreialecu** [comment]
Hey @zoontek!

Looking forward to this being merged.

I just tested it and it appears that it works well on Android, but on iOS it's erroring with:

```
TypeError: null is not an object (evaluating 'NativeModule.statusBarHeight') 
```

simulator_screenshot_1F65A0C3-F0C4-47DC-AD8D-B48CA4BF6A04

**Comment by cristianoccazinsp** [comment]
Curious about this release. I've been using `windowBackground` for ages instead of relying on a package like this for splash screens (having an extra activity for it was overkill for me).  However, `windowBackground` has the side effect that when the keyboard opens and `windowSoftInputMode="adjustResize"` is used, the window background is visible for a bit; not too bad, but not too great neither.

Now that you are upgrading this library to only use `windowBackground` and support android 12 I'm considering using it. But how did you solve these two issues (that I've seen when working with android 12)?

- First, when Android's 12 splash screen closes and the RN activity loads, there's a small flash due to the switch between Android's splash screen and the activity windowBackground display. Not a huge issue, but an issue.
- Second, the issue I mentioned above that the background is always visible, and therefore, shown when the keyboard expands still occurs. Have you found a work around for this?  Setting the root view background to white/other color doesn't work if you happen to use a modal or something that ends up rendered in another view hierarchy.

Thanks for the great work!

**Comment by zoontek** [comment]
@cristianoccazinsp  For now, I used a `Dialog` and two different themes + a switching between the two. It works great (even when the keyboard appears), but is unfortunately not compatible with Android 12.
I will switch to AndroidX SplashScreen implementation: https://developer.android.com/reference/kotlin/androidx/core/splashscreen/SplashScreen

**Comment by zoontek** [comment]
A few things about the `4.0.0` release:

- It will require at least React Native 0.65
- On android, `compileSdkVersion` will need to be >= 31, as it will use [androidx.core:core-splashscreen](https://developer.android.com/reference/kotlin/androidx/core/splashscreen/package-summary)
- It will drop support for Android API < 6.0 and iOS < 11.0
- The `show` method will be removed (as it does not exist in the AndroidX package)
- On iOS, dropping the `show` method will allow relying only on `RCTRootView` `loadingView`

**Comment by happyfloat** [comment]
Could you also please add your notes on how to do dark/light mode themes with this version? I only found that issue: https://github.com/zoontek/react-native-bootsplash/issues/73
Thank you very much!

**Comment by zoontek** [comment]
> Could you also please add your notes on how to do dark/light mode themes with this version? I only found that issue: #73
> Thank you very much!

When it will be ready.

**Comment by cristianoccazinsp** [comment]
Dropping support for iOS 11 may be be a bit too much? Wouldn't it be logical to stay with RN support (e.g., >= 11) ?

**Comment by zoontek** [comment]
@cristianoccazinsp iOS **<** 11.0

**Comment by nschild** [comment]
@cristianoccazinsp With Apples's huge security fix this week, I think most users will be forced to 14.8, which is supported way back to the 6s.

**Comment by zoontek** [comment]
I'm currently struggle with AndroidX splash screen which does not respect asset size, similarly to this topic: https://stackoverflow.com/questions/68687375/is-there-a-way-to-change-the-shape-of-the-splash-screen-icon-in-android-12 (I'm using the alpha02 version)

If any one know how to fix this, don't hesitate.

**Comment by zoontek** [comment]
A small update on this: I finally, after digging in the Android X source code, got the computation right! I currently work on the generator which need to accept SVG files 💪

**Comment by zoontek** [comment]
After a **lot** of work, I'm happy to announce that the first beta is available 🎉. As usual, you can install it with `yarn add react-native-bootsplash@next`

A few things:
- I have to drop the idea of using SVG: it's doable, but it cannot be generated using the CLI easily. But raster images works great!
- The `bootsplash.xml` file, the `SplashScreenActivity` are gone! The setup on Android is way easier now.
- Because AndroidX splash screen module make status and navigation bars transparent, I had to ship a new module to handle that: https://github.com/zoontek/react-native-bars (it's optional, but nicer!). You can find a full example with it in the `/example` directory.

Check this:

https://user-images.githubusercontent.com/1902323/141706056-7d642e6c-6584-4566-a259-2e03a798134e.mp4

**Comment by zoontek** [comment]
I merged it on master: https://github.com/zoontek/react-native-bootsplash/blob/master/README.md

**Comment by zoontek** [comment]
The `MIGRATION.md` guide has been updated: https://github.com/zoontek/react-native-bootsplash/blob/master/MIGRATION.md

**Comment by alleniver** [comment]
good work. man

**Comment by alleniver** [comment]
great work. man

**Comment by creat-or** [comment]
really cool, thank you for your work!

If I may add it here, I found some problems with the new version:
* (Emulator with Android 9, 4.0.0-beta.3): My logo gets cut out by a circular mask. Is this something you experienced, too?

* (Huawei P20 Lite with Android 9, 4.0.0-beta.3): It seems that it loads a very small version of the logo -> 


I generated it by following the instructions
```
yarn react-native generate-bootsplash app/assets/splashscreen/logoVertikalClaimWeiss.png \
  --background-color=FFA900 \
  --logo-width=180 \
  --assets-path=app/assets/splashscreen \
  --flavor=main
```

**Comment by zoontek** [comment]
@creat-or Did you regenerate your android assets to include padding (and check that every old `mipmap-XXXX/bootsplash_logo.png` has been overwritten)? It must look like this: https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
If yes, could you publish your `styles.xml`?

The round mask is unfortunately an android new SplashScreen API constraint (it's bad, right?): https://developer.android.com/guide/topics/ui/splash-screen

**Comment by creat-or** [comment]
@zoontek Thank you very much. I don't know what exactly changed now, but the trick was to completely uninstall and reinstall the app. Also the original image was a bit smaller than 1000x1000 before. 
Anyways, now it seems to work!

**Comment by zoontek** [comment]
@creat-or It could be related to on-device caching. Once the images are generated, the mask is not an issue under 192dp. I added a warning in the CLI: https://github.com/zoontek/react-native-bootsplash/blob/master/react-native.config.js#L49

**Comment by zoontek** [comment]
The stable version has been published: https://github.com/zoontek/react-native-bootsplash/releases/tag/4.0.0

**Comment by a-eid** [comment]
@zoontek it's unfortunate that you had to remove the `show` method, would the splash screen show if you reload the bundle ( react-native-restart ) ? 

is there any workarounds to show the splash screen temporarily when reloading the app ?

**Comment by zoontek** [comment]
No, and no 😕
I could do it on iOS, but it's not doable on Android

**Comment by sudoersfile** [comment]
Hi @zoontek, I love the work you're doing so far with this library. I have a question about migrating to react-native-bootsplash `4.0.0` - is it possible to add dark mode styles for the bootsplash on Android? I see that @happyfloat asked this question in this very issue a while ago, but I don't seem to see any updated documentation about it (other than for version 3).

This isn't too important right now so if it's not ready at the moment, I understand :)

**Comment by zoontek** [comment]
@sudoersfile It already supports dark mode on both platform without any specific trick.

In short:

On Android: copy and paste your `res/values` directory to `res/values-night`, change the colors.
On iOS: Replace the background color with a system one 👇

Screenshot 2021-11-25 at 13 12 40

More infos:
- https://developer.android.com/guide/topics/ui/look-and-feel/darktheme
- https://developer.apple.com/documentation/uikit/appearance_customization/supporting_dark_mode_in_your_interface
- https://brainsandbeards.com/blog/how-to-add-a-dark-mode-splash-screen-to-a-react-native-app

I let you dig documentation, it's not very hard to achieve.

**Comment by sudoersfile** [comment]
Thank for your quick response @zoontek! Got it working now :)

**Comment by a-eid** [comment]
@zoontek following on ""removing the show method"", would it be possible to display some view ( from native or JS ) while reloading the JS bundle.

**Comment by zoontek** [comment]
@a-eid Not anymore.

**Pull request closed without merging**
