### PR TITLE
Added Web Platform support (react-native-web)

### PR DESCRIPTION
**Pull request by kuasha420**
Added support so hide and show methods can be called from JavaScript with desired results. 

The 'native' setup part for web is mostly on the entrypoint (index.html) so I've added instruction in the README.md. 

I mostly done this for my personal project. Let me know anything else needs to be done to make it 'merge material' or web is out of scope for this project. 

Thanks.

### CODE REVIEW

**Comment by sayem314** [comment]
@zoontek any updates?

@kuasha420 can you please use separate `index.web.js` instead of using platform?

**Comment by kuasha420** [comment]
I will resubmit this PR for updated version of RNB if the interest is there.

**Comment by zoontek** [comment]
@kuasha420 @sayem314 Sorry, I didn't have time to check it properly!
Could you update it for the existing codebase? (with and separated `.web.ts` file

**Comment by kuasha420** [comment]
Closing this one since I've submitted another pr for the latest tree [here](https://github.com/zoontek/react-native-bootsplash/pull/248)

**Pull request closed without merging**
