### PR TITLE
Only include desired files in npm package

### LINKED ISSUE #127: Unexpected files included in npmjs distribution
When you look at the files included in the distribution on npmjs it is clear some are development files and shouldn't be there

./android/idea
./android/**/*iml
./android/.gradle
yarn-error.log

I had a similar problem - because it's really confusing to get correct! https://github.com/react-native-community/react-native-device-info/pull/872

Once it is understood though, it's not hard to fix, for example: https://github.com/th3rdwave/react-native-safe-area-context/pull/41/files

Interested in a fix up here?

### PR DESCRIPTION
**Pull request by mikehardy**
Uses method of positively including files and directories at top-level,
then excluding files in specific sub-directories for maximum control

Fixes #127 

This is based off the work from @friederbluemle from https://github.com/react-native-community/react-native-device-info/pull/872 (thanks again Frieder! I am sorry in advance for when I accidentally upgrade react out of step with react-native again at some point in the future :rofl:)

Before:

```
mike@isabela:~/work/react-random/react-native-bootsplash/TEMP (master) % wget https://registry.npmjs.org/react-native-bootsplash/-/react-native-bootsplash-2.2.4.tgz
--2020-06-30 13:19:09--  https://registry.npmjs.org/react-native-bootsplash/-/react-native-bootsplash-2.2.4.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 104.16.20.35, 104.16.24.35, 104.16.19.35, ...
Connecting to registry.npmjs.org (registry.npmjs.org)|104.16.20.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 594565 (581K) [application/octet-stream]
Saving to: ‘react-native-bootsplash-2.2.4.tgz’

react-native-bootsplash-2.2.4.tgz        100%[================================================================================>] 580.63K  2.46MB/s    in 0.2s    

2020-06-30 13:19:09 (2.46 MB/s) - ‘react-native-bootsplash-2.2.4.tgz’ saved [594565/594565]

mike@isabela:~/work/react-random/react-native-bootsplash/TEMP (master) % tar -ztvf react-native-bootsplash-2.2.4.tgz 
-rw-r--r-- 0/0             199 1985-10-26 03:15 package/.editorconfig
-rw-r--r-- 0/0              67 1985-10-26 03:15 package/.prettierignore
-rw-r--r-- 0/0              29 1985-10-26 03:15 package/.prettierrc
-rw-r--r-- 0/0              16 1985-10-26 03:15 package/.yarnrc
-rw-r--r-- 0/0              27 1985-10-26 03:15 package/CODEOWNERS
-rw-r--r-- 0/0            1076 1985-10-26 03:15 package/LICENSE
-rw-r--r-- 0/0           45824 1985-10-26 03:15 package/android/.gradle/5.4.1/executionHistory/executionHistory.bin
-rw-r--r-- 0/0           19197 1985-10-26 03:15 package/android/.gradle/5.4.1/fileHashes/fileHashes.bin
-rw-r--r-- 0/0               1 1985-10-26 03:15 package/android/.gradle/5.4.1/fileChanges/last-build.bin
-rw-r--r-- 0/0           53177 1985-10-26 03:15 package/android/.gradle/buildOutputCleanup/outputFiles.bin
-rw-r--r-- 0/0            1424 1985-10-26 03:15 package/android/build.gradle
-rwxr-xr-x 0/0             322 1985-10-26 03:15 package/ios/RNBootSplash.h
-rw-r--r-- 0/0           13246 1985-10-26 03:15 package/android/android.iml
-rw-r--r-- 0/0             463 1985-10-26 03:15 package/android/build/generated/source/buildConfig/androidTest/debug/com/zoontek/rnbootsplash/test/BuildConfig.java
-rw-r--r-- 0/0             673 1985-10-26 03:15 package/android/build/generated/source/buildConfig/debug/com/zoontek/rnbootsplash/BuildConfig.java
-rw-r--r-- 0/0            3321 1985-10-26 03:15 package/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplash.java
-rw-r--r-- 0/0            1144 1985-10-26 03:15 package/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java
-rw-r--r-- 0/0            1802 1985-10-26 03:15 package/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java
-rw-r--r-- 0/0             692 1985-10-26 03:15 package/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashPackage.java
-rwxr-xr-x 0/0           12104 1985-10-26 03:15 package/scripts/generate.js
-rw-r--r-- 0/0             312 1985-10-26 03:15 package/index.js
-rw-r--r-- 0/0             293 1985-10-26 03:15 package/android/build/intermediates/aapt_friendly_merged_manifests/debug/aapt/output.json
-rw-r--r-- 0/0             308 1985-10-26 03:15 package/android/build/intermediates/merged_manifests/debug/output.json
-rw-r--r-- 0/0             265 1985-10-26 03:15 package/android/build/intermediates/merged_manifests/debugAndroidTest/output.json
-rw-r--r-- 0/0            1266 1985-10-26 03:15 package/package.json
-rw-r--r-- 0/0              17 1985-10-26 03:15 package/android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
-rw-r--r-- 0/0              17 1985-10-26 03:15 package/android/.gradle/5.4.1/executionHistory/executionHistory.lock
-rw-r--r-- 0/0              17 1985-10-26 03:15 package/android/.gradle/5.4.1/fileHashes/fileHashes.lock
-rw-r--r-- 0/0          260221 1985-10-26 03:15 package/yarn-error.log
-rwxr-xr-x 0/0            4044 1985-10-26 03:15 package/ios/RNBootSplash.m
-rw-r--r-- 0/0            3224 1985-10-26 03:15 package/.github/CODE_OF_CONDUCT.md
-rw-r--r-- 0/0             715 1985-10-26 03:15 package/.github/ISSUE_TEMPLATE.md
-rw-r--r-- 0/0           12973 1985-10-26 03:15 package/README.md
-rwxr-xr-x 0/0            7326 1985-10-26 03:15 package/ios/RNBootSplash.xcodeproj/project.pbxproj
-rw-r--r-- 0/0             238 1985-10-26 03:15 package/ios/RNBootSplash.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
-rw-r--r-- 0/0          446004 1985-10-26 03:15 package/scripts/screenshot.png
-rw-r--r-- 0/0             572 1985-10-26 03:15 package/RNBootSplash.podspec
-rw-r--r-- 0/0              52 1985-10-26 03:15 package/android/.gradle/buildOutputCleanup/cache.properties
-rw-r--r-- 0/0               0 1985-10-26 03:15 package/android/.gradle/5.4.1/gc.properties
-rw-r--r-- 0/0               0 1985-10-26 03:15 package/android/.gradle/vcs-1/gc.properties
-rw-r--r-- 0/0             348 1985-10-26 03:15 package/android/local.properties
-rw-r--r-- 0/0             689 1985-10-26 03:15 package/ReactNativeBootSplash.re
-rw-r--r-- 0/0             448 1985-10-26 03:15 package/android/.idea/caches/build_file_checksums.ser
-rw-r--r-- 0/0          119701 1985-10-26 03:15 package/android/.idea/caches/gradle_models.ser
-rw-r--r-- 0/0             370 1985-10-26 03:15 package/index.d.ts
-rw-r--r-- 0/0            3010 1985-10-26 03:15 package/android/build/intermediates/manifest_merge_blame_file/debugAndroidTest/manifest-merger-blame-debug-androidTest-report.txt
-rw-r--r-- 0/0             440 1985-10-26 03:15 package/android/build/intermediates/manifest_merge_blame_file/debug/manifest-merger-blame-debug-report.txt
-rw-r--r-- 0/0            1991 1985-10-26 03:15 package/android/build/outputs/logs/manifest-merger-debug-report.txt
-rw-r--r-- 0/0            2880 1985-10-26 03:15 package/ios/RNBootSplash.xcodeproj/xcshareddata/xcschemes/RNBootSplash.xcscheme
-rw-r--r-- 0/0           11161 1985-10-26 03:15 package/ios/RNBootSplash.xcodeproj/project.xcworkspace/xcuserdata/zoontek.xcuserdatad/UserInterfaceState.xcuserstate
-rw-r--r-- 0/0             135 1985-10-26 03:15 package/ios/RNBootSplash.xcodeproj/project.xcworkspace/contents.xcworkspacedata
-rw-r--r-- 0/0             252 1985-10-26 03:15 package/android/build/intermediates/aapt_friendly_merged_manifests/debug/aapt/AndroidManifest.xml
-rw-r--r-- 0/0             252 1985-10-26 03:15 package/android/build/intermediates/library_manifest/debug/AndroidManifest.xml
-rw-r--r-- 0/0             759 1985-10-26 03:15 package/android/build/intermediates/merged_manifests/debugAndroidTest/AndroidManifest.xml
-rw-r--r-- 0/0             156 1985-10-26 03:15 package/android/src/main/AndroidManifest.xml
-rw-r--r-- 0/0             753 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_annotation_annotation_1_0_0_jar.xml
-rw-r--r-- 0/0             834 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_appcompat_appcompat_1_0_2_aar.xml
-rw-r--r-- 0/0             559 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_arch_core_core_common_2_0_0_jar.xml
-rw-r--r-- 0/0             668 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_arch_core_core_runtime_2_0_0_aar.xml
-rw-r--r-- 0/0             723 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_asynclayoutinflater_asynclayoutinflater_1_0_0_aar.xml
-rw-r--r-- 0/0             557 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_collection_collection_1_0_0_jar.xml
-rw-r--r-- 0/0             898 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_coordinatorlayout_coordinatorlayout_1_0_0_aar.xml
-rw-r--r-- 0/0             794 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_core_core_1_0_1_aar.xml
-rw-r--r-- 0/0             681 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_cursoradapter_cursoradapter_1_0_0_aar.xml
-rw-r--r-- 0/0             660 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_customview_customview_1_0_0_aar.xml
-rw-r--r-- 0/0             674 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_documentfile_documentfile_1_0_0_aar.xml
-rw-r--r-- 0/0             858 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_drawerlayout_drawerlayout_1_0_0_aar.xml
-rw-r--r-- 0/0             826 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_fragment_fragment_1_0_0_aar.xml
-rw-r--r-- 0/0             674 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_interpolator_interpolator_1_0_0_aar.xml
-rw-r--r-- 0/0             712 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_legacy_legacy_support_core_ui_1_0_0_aar.xml
-rw-r--r-- 0/0             727 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_legacy_legacy_support_core_utils_1_0_0_aar.xml
-rw-r--r-- 0/0             584 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_lifecycle_lifecycle_common_2_0_0_jar.xml
-rw-r--r-- 0/0             698 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_lifecycle_lifecycle_livedata_2_0_0_aar.xml
-rw-r--r-- 0/0             723 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_lifecycle_lifecycle_livedata_core_2_0_0_aar.xml
-rw-r--r-- 0/0             693 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_lifecycle_lifecycle_runtime_2_0_0_aar.xml
-rw-r--r-- 0/0             703 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_lifecycle_lifecycle_viewmodel_2_0_0_aar.xml
-rw-r--r-- 0/0             632 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_loader_loader_1_0_0_aar.xml
-rw-r--r-- 0/0             736 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_localbroadcastmanager_localbroadcastmanager_1_0_0_aar.xml
-rw-r--r-- 0/0             802 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_print_print_1_0_0_aar.xml
-rw-r--r-- 0/0             709 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_slidingpanelayout_slidingpanelayout_1_0_0_aar.xml
-rw-r--r-- 0/0             906 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_swiperefreshlayout_swiperefreshlayout_1_0_0_aar.xml
-rw-r--r-- 0/0             688 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_vectordrawable_vectordrawable_1_0_1_aar.xml
-rw-r--r-- 0/0             733 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_vectordrawable_vectordrawable_animated_1_0_0_aar.xml
-rw-r--r-- 0/0             723 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_versionedparcelable_versionedparcelable_1_0_0_aar.xml
-rw-r--r-- 0/0             653 1985-10-26 03:15 package/android/.idea/libraries/Gradle__androidx_viewpager_viewpager_1_0_0_aar.xml
-rw-r--r-- 0/0             783 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_fbjni_fbjni_java_only_0_0_3_jar.xml
-rw-r--r-- 0/0             828 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_fresco_drawee_2_0_0_aar.xml
-rw-r--r-- 0/0            1006 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_fresco_fbcore_2_0_0_aar.xml
-rw-r--r-- 0/0            1006 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_fresco_fresco_2_0_0_aar.xml
-rw-r--r-- 0/0            1062 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_fresco_imagepipeline_2_0_0_aar.xml
-rw-r--r-- 0/0            1102 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_fresco_imagepipeline_base_2_0_0_aar.xml
-rw-r--r-- 0/0             933 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_fresco_imagepipeline_okhttp3_2_0_0_aar.xml
-rw-r--r-- 0/0             912 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_fresco_nativeimagefilters_2_0_0_aar.xml
-rw-r--r-- 0/0             933 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_fresco_nativeimagetranscoder_2_0_0_aar.xml
-rw-r--r-- 0/0             842 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_infer_annotation_infer_annotation_0_11_2_jar.xml
-rw-r--r-- 0/0             985 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_react_react_native_0_62_2_aar.xml
-rw-r--r-- 0/0             861 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_soloader_annotation_0_8_0_aar.xml
-rw-r--r-- 0/0             775 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_soloader_nativeloader_0_8_0_jar.xml
-rw-r--r-- 0/0             847 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_soloader_soloader_0_8_0_aar.xml
-rw-r--r-- 0/0             821 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_facebook_yoga_proguard_annotations_1_14_1_jar.xml
-rw-r--r-- 0/0             744 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_google_code_findbugs_jsr305_3_0_2_jar.xml
-rw-r--r-- 0/0             736 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_squareup_okhttp3_okhttp_3_12_1_jar.xml
-rw-r--r-- 0/0             834 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_squareup_okhttp3_okhttp_urlconnection_3_12_1_jar.xml
-rw-r--r-- 0/0             710 1985-10-26 03:15 package/android/.idea/libraries/Gradle__com_squareup_okio_okio_1_15_0_jar.xml
-rw-r--r-- 0/0             711 1985-10-26 03:15 package/android/.idea/libraries/Gradle__javax_inject_javax_inject_1_jar.xml
-rw-r--r-- 0/0             634 1985-10-26 03:15 package/android/.idea/gradle.xml
-rw-r--r-- 0/0              76 1985-10-26 03:15 package/android/src/main/res/values/ids.xml
-rw-r--r-- 0/0             357 1985-10-26 03:15 package/android/.idea/misc.xml
-rw-r--r-- 0/0             254 1985-10-26 03:15 package/android/.idea/modules.xml
-rw-r--r-- 0/0            3309 1985-10-26 03:15 package/android/.idea/codeStyles/Project.xml
-rw-r--r-- 0/0             564 1985-10-26 03:15 package/android/.idea/runConfigurations.xml
-rw-r--r-- 0/0             183 1985-10-26 03:15 package/android/.idea/vcs.xml
-rw-r--r-- 0/0            4859 1985-10-26 03:15 package/android/.idea/workspace.xml
-rw-r--r-- 0/0              65 1985-10-26 03:15 package/.github/FUNDING.yml


```

After:

```
mike@isabela:~/work/react-random/react-native-bootsplash (issue127-npm-files) % npm pack --dry-run
npm notice 
npm notice 📦  react-native-bootsplash@2.2.4
npm notice === Tarball Contents === 
npm notice 15B    scripts/.npmignore                                                      
npm notice 27B    CODEOWNERS                                                              
npm notice 1.1kB  LICENSE                                                                 
npm notice 1.4kB  android/build.gradle                                                    
npm notice 322B   ios/RNBootSplash.h                                                      
npm notice 3.3kB  android/src/main/java/com/zoontek/rnbootsplash/RNBootSplash.java        
npm notice 1.1kB  android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java
npm notice 1.8kB  android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java  
npm notice 692B   android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashPackage.java 
npm notice 12.1kB scripts/generate.js                                                     
npm notice 312B   index.js                                                                
npm notice 1.5kB  package.json                                                            
npm notice 4.0kB  ios/RNBootSplash.m                                                      
npm notice 13.0kB README.md                                                               
npm notice 7.3kB  ios/RNBootSplash.xcodeproj/project.pbxproj                              
npm notice 572B   RNBootSplash.podspec                                                    
npm notice 689B   ReactNativeBootSplash.re                                                
npm notice 370B   index.d.ts                                                              
npm notice 2.9kB  ios/RNBootSplash.xcodeproj/xcshareddata/xcschemes/RNBootSplash.xcscheme 
npm notice 156B   android/src/main/AndroidManifest.xml                                    
npm notice 76B    android/src/main/res/values/ids.xml                                     
npm notice === Tarball Details === 
npm notice name:          react-native-bootsplash                 
npm notice version:       2.2.4                                   
npm notice filename:      react-native-bootsplash-2.2.4.tgz       
npm notice package size:  15.6 kB                                 
npm notice unpacked size: 52.8 kB                                 
npm notice shasum:        8811df705721ffe300baf66606c6670cf80daf7f
npm notice integrity:     sha512-XOSnTOSOTqD6s[...]mfiTEUgC/k7QQ==
npm notice total files:   21                                      
npm notice 
react-native-bootsplash-2.2.4.tgz

```

### CODE REVIEW

**Comment by friederbluemle** [comment]
Very nice! :+1:

Small optimization tip: You can also remove `index.js` (declared as `main`), as well as `LICENSE`, `package.json`, and `README.md` from the `files` array. They will *always* be included (no need to explicitly mention them): https://docs.npmjs.com/files/package.json#files Also, the `CODEOWNERS` file is specific to GitHub and typically not published (just like `.github/` is not published). So you can also consider removing it from the array.

And another tip: Instead of manually downloading and extracting a tarball from npm, you can achieve the same with a simple oneliner:

```sh
npm pack --dry-run <package@version>
```

e.g. to check the package contents of `react-native-bootsplash@2.2.4`:

```sh
npm pack --dry-run react-native-bootsplash@2.2.4
```

**Comment by mikehardy** [comment]
Nice tip on the specific files, I'll re-push in a moment - I wasn't sure about index.js specifically and the others are nice fine tuning

I had to manually download because the files that are currently published in the live tarball include build artifacts that you only see if you are doing compilation etc in your dev workspace (which I wasn't), so I wasn't able to show all the .idea / .gradle junk unless I pulled form npmjs live :-)

**Comment by mikehardy** [comment]
Oh nice @friederbluemle that one-liner checks out. And confirmed after pruning the files array with your suggestions the results are still pretty:

```
mike@isabela:~/work/react-random/react-native-bootsplash (issue127-npm-files) % npm pack --dry-run
npm notice 
npm notice 📦  react-native-bootsplash@2.2.4
npm notice === Tarball Contents === 
npm notice 15B    scripts/.npmignore                                                      
npm notice 1.1kB  LICENSE                                                                 
npm notice 1.4kB  android/build.gradle                                                    
npm notice 322B   ios/RNBootSplash.h                                                      
npm notice 3.3kB  android/src/main/java/com/zoontek/rnbootsplash/RNBootSplash.java        
npm notice 1.1kB  android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java
npm notice 1.8kB  android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java  
npm notice 692B   android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashPackage.java 
npm notice 12.1kB scripts/generate.js                                                     
npm notice 312B   index.js                                                                
npm notice 1.4kB  package.json                                                            
npm notice 4.0kB  ios/RNBootSplash.m                                                      
npm notice 13.0kB README.md                                                               
npm notice 7.3kB  ios/RNBootSplash.xcodeproj/project.pbxproj                              
npm notice 572B   RNBootSplash.podspec                                                    
npm notice 689B   ReactNativeBootSplash.re                                                
npm notice 370B   index.d.ts                                                              
npm notice 2.9kB  ios/RNBootSplash.xcodeproj/xcshareddata/xcschemes/RNBootSplash.xcscheme 
npm notice 156B   android/src/main/AndroidManifest.xml                                    
npm notice 76B    android/src/main/res/values/ids.xml                                     
npm notice === Tarball Details === 
npm notice name:          react-native-bootsplash                 
npm notice version:       2.2.4                                   
npm notice filename:      react-native-bootsplash-2.2.4.tgz       
npm notice package size:  15.6 kB                                 
npm notice unpacked size: 52.7 kB                                 
npm notice shasum:        196891c9eb23bb33078b495186a2d16bc9a710aa
npm notice integrity:     sha512-+fniCPKaMJ/tp[...]8YpMDqUK5o78w==
npm notice total files:   20                                      
npm notice 
react-native-bootsplash-2.2.4.tgz
```

I think this is good to go then, and better than it was first attempt

**Comment by zoontek** [comment]
Awesome work!
Just a simple question, is it be possible to merge all the .npmignore files?

```
.DS_Store
.npmignore

android/*.iml
android/.gradle/
android/.idea/
android/build/
android/gradle/
android/gradlew
android/gradlew.bat
android/local.properties

ios/*/project.xcworkspace/
ios/*/xcuserdata/
ios/Pods/
ios/build/

scripts/screenshot.png
```

**Comment by mikehardy** [comment]
I am unsure, that's a question for @friederbluemle who is wiser at the npm pack process than me. 

I have this https://github.com/react-native-community/react-native-device-info/pull/872#issuecomment-548124928

> Yeah, very good observation. :) Just a couple of days ago I was wondering about the same exact thing (leading slash required or not). What I found was that with or without the leading slash, only root directories (basically on the same level as the package.json) are considered.
In other words: The entries in files don't match nested folders (a behavior that's different .gitignore).

Which leads me to believe there is nested-folder idiosynchracy but I am not authoritative

**Comment by Maskedman99** [comment]
Yep npm isn't ignoring files in nested folder.  
Here's a PR from react-native-svg addressing the same issue: https://github.com/react-native-community/react-native-svg/pull/1190
Excited to see the size reduction in new version.

**Comment by zoontek** [comment]
I made a release for it: https://github.com/zoontek/react-native-bootsplash/releases/tag/2.2.5. Thanks @mikehardy !

**Pull request merged**
