### PR TITLE
Allow using layout resource for Android

### PR DESCRIPTION
**Pull request by chochihim**
I have an app where drawable resource is not enough to create the desired splash screen. I need to use a layout resource directly.

If you are okay with this addition, I will also add example in README.

### CODE REVIEW

**Comment by zoontek** [comment]
@chochihim I need to check it on real devices, but it seems like a really good idea and keeping it optional is 💯

**Comment by zoontek** [comment]
@chochihim I started reviewing it and one question bugs me. If a drawable is not enough to create the desired splash screen, how can you set it at app launch?

```xml
<style name="BootTheme" parent="AppTheme">
  <!-- this cannot be done, and cannot be replaced by a drawable since the layout is too complex -->
  <item name="android:background">@layout/layout_resource</item>
</style>
```

**Comment by chochihim** [comment]
@zoontek I do not set the background using any drawable in the theme. I just set a background colour (which is identical to my layout background colour) and this is enough for me.

I noticed that the way I use is not really the [recommended one](https://developer.android.com/topic/performance/vitals/launch-time) to implement splash screen. I think we better stick to the recommended way. Creating extra option seems flexible but might confuses new user.

**Comment by zoontek** [comment]
@chochihim Indeed. By offering more power to new users, they will don't understand why the splash screen might "jump" / interfere with the system UI height (status bar).

The current way is limited, but bullet-proof 🙂

**Pull request closed without merging**
